---
title: "Definition und Beispiele"
---

::: callout-caution
Dieser Bereich befindet sich aktuell im Aufbau.
:::

Mit formaler Forschung sind Vorhaben gemeint, die Phänomene mittels mathematischer Modelle (Formeln) erforschen. Dabei handelt es sich häufig um *a priori*, also ohne vorhergehende empirische Untersuchung, oder aus bestimmten Prämissen logisch folgend geltende Zusammenhänge. Das kann zum Beispiel eine Anwendung von Kirchberg Algebra oder eine Kritik der Bonnay und Westerstahl Lösung zu Carnaps Problem sein. Forschende verwenden dabei mathematische Herleitungen oder Beweise.

Formale Forschung ist vor allem in der Mathematik und Philosophie (z. B. formale Logik) vorzufinden. Darüber hinaus kommt sie jedoch auch in anderen Disziplinen, wie zum Beispiel Informatik oder Physik vor.

# Beispielprojekte

| Disziplin & Subdisziplin | Quellenangabe | Beschreibung |
|--------------------------|---------------|--------------|
|                          |               |              |
