---
title: "Definition und Beispiele"
---

Mit qualitativer Forschung sind Vorhaben gemeint, die Phänomene über verschiedene Medien wie Texte oder Bilder erforschen. Das kann zum Beispiel der Fall der Berliner Mauer aus geschichtlicher Perspektive oder Sprachwandel in der Fernsehwerbung in den 2010er Jahren sein. Ihnen gemeinsam ist, dass sie ein tiefgehendes Verständnis anstreben. Dabei verwenden Ansätze, die zu großen Teilen auf menschlicher Interpretation beruhen, wie zum Beispiel qualitative Inhaltsanalysen, unstrukturierte oder teilstrukturierte Befragungen, oder Beobachtungen.

Qualitative Forschung ist vor allem in den Geisteswissenschaften präsent. Darunter fallen beispielsweise Theologie, Erziehungswissenschaften, Sozialwissenschaften, Geschichte, Philosophie, Philologie, Geowissenschaften, Sportwissenschaften, und Soziologie.

# Beispielprojekte

| Disziplin & Subdisziplin | Quellenangabe | Beschreibung |
|--------------------------|---------------|--------------|
|                          |               |              |
