---
title: "Materialien und Daten"
---

Eine transparente Beschreibung und Bereitstellung der verwendeten Materialien und Daten macht den Forschungsprozess leichter nachvollziehbar und wiederholbar. Reproduzierbarkeit und Replizierbarkeit von Forschungsergebnissen lassen sich dadurch leichter überprüfen und die Wiederverwendung und Weiterentwicklung innovativer Methoden wird erleichtert. Professionelle Open Science-Lösungen unterstützen Forschende bei der transparenten Bereitstellung von Forschungsmaterialien und Forschungsdaten unter Berücksichtigung datenschutzrechtlicher, ethischer und fachspezifischer Anforderungen. Beispiele für spezifische Teillösungen sind:

-   Bereitstellung der verwendeten Fragebogen in einem Codebook und der anonymisierten erhobenen Fragebogendaten einer Umfrage in der Soziologie

-   Führen und Bereitstellen elektronischer Laborbücher in der organischen Chemie

-   Bereitstellung kodierter Beobachtungsdaten und von reproduzierbaren Analyseskripten in der Biologie

-   Verwendung von Open Source Software für die Darstellung von Ergebnissen in den Geowissenschaften

-   Sicherstellung komputationaler Reproduzierbarkeit in der Informatik

-   Pseudonymisierung und Veröffentlichung von medizinischen Daten

-   Aufbereitung und Publikation von Forschungsdaten nach den FAIR-Prinzipien

Im MüCOS werden in enger Abstimmung mit der Datenschutzbeauftragten der Universität Münster, der ULB (Forschungsdatenmanagement, Publikation von Daten über den Datastore) und Anbietern fachspezifischer Lösungen (etwa im Bereich Digital Humanities) Lösungen zur offenen Bereitstellung von Forschungsmaterialien und -daten gesammelt und weiterentwickelt.

## Weiterführende Informationen

-   Datenrepositorien für alle Fachbereiche: <https://www.re3data.org/browse/by-subject/>

-   Disziplinenübergreifende Infrastruktur zum Verwalten, Archivieren, und Veröffentlichen von Forschung: <https://osf.io/>

-   Spielerische Heranführung an die Bedeutung von Meta-Daten zur Nachvollziehbarkeit von Forschungsmaterialien: <https://eprints.gla.ac.uk/196477/4/ReadMe_Sep19.pdf>
