---
title: "Forschungsfragen und Forschungsplanung"
---

Ein offener Forschungsprozess beginnt mit der transparenten Darlegung der adressierten Forschungsfragen (inkl. Forschungshypothesen im Falle konfirmatorischer Forschung) und des Forschungsplans (also einer transparenten Beschreibung der Methoden, mit denen diese Fragen beantwortet werden sollen). Professionelle Open Science-Ansätze unterstützen Forschende dabei, zentrale Fragen und Vorgehensweisen systematisch im Vorhinein festzulegen und hierbei konfirmatorische von explorativen Anteilen zu trennen. Konkrete Open Science Lösungen können dabei zum Beispiel sein:

-   Präregistrierung eines Verhaltensexperiments in den Kommunikationswissenschaften oder einer Sekundärdatenanalyse in den Erziehungs- und Bildungswissenschaften

-   Transparente Dokumentation des geplanten Prozesses der Datengenerierung mittels eines Interview-Leitfadens für eine Fokusgruppe in der Linguistik

-   Erstellung eines vorläufigen PRISMA Flow Charts für eine Meta-Analyse in der Medizin

-   Erstellung eines Registered Reports Stage 1 zu einer geplanten Experience-Sampling-Studie inkl. einer Poweranalyse mittel Datensimulation in der Psychologie

-   Transparente Dokumentation des geplanten Vorgehens bei der Literaturrecherche und -auswahl und der Prinzipien der Quellenanalyse in den Geschichtswissenschaften

Im MüCOS werden sowohl avancierte als auch niedrigschwellige Lösungen zur transparenten Dokumentation von Forschungsfragen und Forschungsplanung bereitgestellt. Dies umfasst disziplinübergreifende Lösungen als auch Lösungen, die für die spezifischen Anforderungen und Herausforderungen einzelner Disziplinen maßgeschneidert sind. Hierbei werden sowohl Unterstützungsangebote der Universitäts- und Landesbibliothek Münster im Bereich der Literatursuche und Literaturverwaltung als auch fachspezifische Unterstützungsangebote (bspw. SCDH im Bereich der Digital Humanities) integriert.

## Context of Discovery und Context of Justification

Forschung unterscheidet sich dahingehend, wie eng der Fokus ist, also ob besondere Zufallsbefunde möglich sind oder nicht. Bei einer archäologischen Ausgrabung können Forschende zum Beispiel Relikte aus einer anderen Zeit ausgraben als erwartet. Bei einem physikalischen Experiment hingegen ist es weniger üblich, dass beobachtete Messungen stark von der Erwartung abweichen. In der Wissenschaftstheorie wird gelegentlich zwischen dem Kontext, in dem eine Entdeckung gemacht wurde, und dem Kontext, in dem sie gerechtfertigt wird (z. B. im Forschungsbericht) unterschieden. Gelegentlich ist der Entdeckungs-Kontext (Context of Discovery) völlig unerheblich: Ob jemand die Idee für einen mathematischen Beweis beim Bahnfahren oder im Traum hatte, spielt keine Rolle für die Wahrheit und Rechtfertigung des Wahrheitsanspruches (Context of Justification). In anderen Fällen kann er aber hoch relevant und identisch mit dem Context of Justification sein: Wenden Forschende viele verschiedene statistische Modelle und Verfahren an einem Datensatz an, entdecken dort einen besonders guten Algorithmus, und kommunizieren ihn als den, den sie von Beginn an als besten Algorithmus vermutet hätten, entsteht das Problem des *Overfitting* oder HARKing (Hypothesizing after the results are known). Dies ist vor allem möglich in Fällen, bei denen die Daten aus Signal und Rauschen bestehen und eine Post Hoc Erklärung nicht dazwischen differenzieren kann.

## Weiterführende Informationen

-   Informationen zu elektronischen Laborbüchern und der eLab Software sind auf den FDM-Seiten der Uni Münster gesammelt: <https://www.uni-muenster.de/Forschungsdaten/angebote/werkzeuge/elabftw.html>

-   Diskussion des Unterschiedes zwischen Vorhersage und Post-Hoc Erklärung in den Natur- und Sozialwissenschaften: <https://doi.org/10.1073/pnas.1708274114>
