---
title: "Forschungsergebnisse veröffentlichen"
---

Wissenschaftliche Ergebnisse lassen sich auf vielfältige Weise veröffentlichen und die angebotenen und genutzten Publikationsformate werden vielfältiger. Im Rahmen eines professionellen Open Science-Ansatzes können Forschende dabei unterstützt werden im Spannungsfeld von Renommee, Kosten, Qualitätssicherung und Zugänglichkeit die für den jeweiligen Fall optimale Veröffentlichungsstrategie abzuleiten. Hierzu gehören etwa:

-   Auswahl von Open Access-Optionen bei einer gegebenen Zielzeitschrift (z.B. Moving Wall vs. Green Open Access)

-   Veröffentlichung einer Studie mit offener Begutachtung über Peer-Community-In Plattform in der Mikrobiologie

-   Auswahl eines Pre-Print Servers für eine epidemiologische Studie

-   Transparente Darstellung von Autor\*innenbeiträgen mittels standardisierter Taxonomien (z.B. CRediT)

-   Gründung einer von Wissenschaftler\*innen geführten Diamond Open Access Zeitschrift

Das MüCOS bündelt die Expertise zur transparenten Veröffentlichung von Forschungsergebnissen in enger Abstimmung mit vorhandenen spezifischen Angeboten: Die Universitäts- und Landesbibliothek Münster berät zu Open Access und digitalem Publizieren, verwaltet zahlreiche Open-Access-Zeitschriften, den Publikationsserver Miami, bietet Beratung und Unterstützung bei der Gründung neuer Open-Access Zeitschriften sowie Migration von Journals auf das Open Journal System.
