---
title: "Themen und Ansprechpersonen"
---

Der Bereich Open Science kann durch die Vielfalt schnell überfordern. Hier erhalten Sie eine kurze Zusammenfassung typischer Themen. Für einen Großteil der relevanten Aspekte hat die Universität Münster für ihre Angehörigen bereits Beratungsangebot.

|                                             |     |                                                         |                                                                                                                                                                                                                                                                                                        |                                                                                                                                        |                                        |                                                                          |
|---------------------------------------------|-----|---------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------|--------------------------------------------------------------------------|
| **Themenkomplex**                           |     | **Thema**                                               | **Erklärung**                                                                                                                                                                                                                                                                                          | **Zu lösendes Problem**                                                                                                                | **Ansprechperson**                     | **Website**                                                              |
| 0\. Übergreifend                            |     | Big Team Science                                        | Große Gruppen von Forschenden arbeiten häufig international und interdisziplinär im Rahmen eines Projektes gemeinsam                                                                                                                                                                                   | Fördert Austausch und Zusammenarbeit, Erlaubt Untersuchung von Fragestellungen, die enorme Ressourcen benötigen                        | MüCOS                                  | <https://www.uni-muenster.de/MueCOS/index.html>                          |
| 0\. Übergreifend                            |     | Citizen Science                                         | Bürger\*innen werden aktiv in den Wissenschaftsprozess mit einbezogen                                                                                                                                                                                                                                  | Fördert Transfer, erhöht Vertrauen in Wissenschaft, bietet neue Perspektiven auf Forschungsgegenstand                                  | Arbeitsstelle Forschungstransfer       | <https://www.uni-muenster.de/AFO/citizen_science/index.shtml>            |
| 0\. Übergreifend                            |     | Open Governance                                         | Institutionelle Verfahren und Entscheidungen werden offengelegt                                                                                                                                                                                                                                        | Erhöht evtl. Vertrauen in und Akzeptanz von Führungsentscheidungen, verbessert evtl. Entscheidungsqualität                             | ---                                    | ---                                                                      |
| 1\. Forschungsfragen und Forschungssplanung |     | Präregistrierung                                        | Hypothesen und Analyseplan werden vor der Studiendurchführung klar definiert und online mit Zeitstempel gespeichert (Embargo möglich)                                                                                                                                                                  | Verhindert das Ausnutzen von Flexibilitäten in der Datenanalyse und erhöht Vertrauenswürdigkeit von Ergebnissen                        | MüCOS                                  | <https://www.uni-muenster.de/MueCOS/index.html>                          |
| 1\. Forschungsfragen und Forschungssplanung |     | Sample Size Justification                               | Die benötigte Menge an Beobachtungen wird im Vorhinein durch Überlegungen, Poweranalysen, oder Datensimulationen festgelegt                                                                                                                                                                            | Erhöht Effizienz von Forschung und Präzision von Aussagen                                                                              | Angebote des jeweiligen Faches         | ---                                                                      |
| 1\. Forschungsfragen und Forschungssplanung |     | Theorien spezifizieren                                  | Die Aussagen von Theorien werden präzisiert, beispielsweise durch die Überführung in ein mathematisches Modell (Formalisierung)                                                                                                                                                                        | Vereinfacht Prüfung und Widerlegung wissenschaftlicher Theorien                                                                        | Angebote des jeweiligen Faches         | ---                                                                      |
| 1\. Forschungsfragen und Forschungssplanung |     | Registered Report                                       | Zusätzlicher Schritt im Publikationsprozess, bei dem der Artikel bereits vor der Erhebung der Daten begutachtet wird. Akzeptanz in diesem Stadium bedeutet eine Zusage zur Veröffentlichung unabhängig der Ergebnisse der Studie (unter der Bedingung, dass die Studie wie geplant durchgeführt wird). | Verhindert, dass Studien mit unerwarteten oder unklaren Ergebnissen in der Schublade landen und beugt dem Publikationsbias vor         | MüCOS                                  | <https://www.uni-muenster.de/MueCOS/index.html>                          |
| 2\. Materialien und Daten                   |     | Open Materials                                          | Materialien werden mit einer Lizenz zur Nachnutzung online veröffentlicht                                                                                                                                                                                                                              | Erleichtert das Nachvollziehen der Forschung sowie Replikationsversuche                                                                | MüCOS                                  | <https://www.uni-muenster.de/MueCOS/index.html>                          |
| 2\. Materialien und Daten                   |     | Reproducible Code                                       | Programme und Code/Syntax lassen sich durch Dritte so durchführen, dass sie damit die berichteten Ergebnisse ebenfalls erhalten                                                                                                                                                                        | Verringert Anteil an Rechen- und Übertragungsfehlern                                                                                   | MüCOS                                  | <https://www.uni-muenster.de/MueCOS/index.html>                          |
| 2\. Materialien und Daten                   |     | Open Data                                               | Forschungsdaten werden online veröffentlicht und zur Nachnutzung aufbereitet (z.B. via FAIR Kriterien und mit Codebook)                                                                                                                                                                                | Spart Kosten (z.B. weil Daten nicht erneut erhoben werden msüsen), erleichtert kumulative Forschung                                    | Service Center for Data Management     | <https://www.uni-muenster.de/Forschungsdaten/>                           |
| 2\. Materialien und Daten                   |     | Anonymisierung von Daten                                | Persönliche Informationen werden in Daten unkenntlich gemacht oder aus ihnen entfernt                                                                                                                                                                                                                  | Einhaltung von ethischen und rechtlichen Anforderungen                                                                                 | Angebote des jeweiligen Faches         | ---                                                                      |
| 2\. Materialien und Daten                   |     | Reproduktion, Replikation                               | Bisherige Befunde werden erneut mit denselben oder anderen Daten geprüft                                                                                                                                                                                                                               | Test der Robustheit und Vertrauenswürdigkeit wissenschaftlicher Befunde                                                                | MüCOS                                  | <https://www.uni-muenster.de/MueCOS/index.html>                          |
| 2\. Materialien und Daten                   |     | Open Source                                             | Der Quellcode von Programmen wird online veröffentlicht und andere Forschende können ihn ohne Einschränkungen weiterverwenden                                                                                                                                                                          | Ermöglicht Qualitätskontrolle, verhindert vendor-lock-in                                                                               | Angebote des jeweiligen Faches         | ---                                                                      |
| 3\. Forschungsergebnisse veröffentlichen    |     | Open Access                                             | Forschungsoutput (Artikel, Bücher, Daten, Software, Lehrmaterialien, ...) werden online veröffentlicht                                                                                                                                                                                                 | Erleichtert Zugänglichkeit und ermöglicht Qualitätskontrolle                                                                           | Publizieren an der Universität Münster | <https://www.uni-muenster.de/Publizieren/open-access/>                   |
| 3\. Forschungsergebnisse veröffentlichen    |     | Preprints                                               | Forschungsartikel werden nach der Fertigstellung und vor der Einreichung bei einer Fachzeitschrift bzw. vor der dortigen Veröffentlichung auf einem institutionellen oder externen Repositorium/Server veröffentlicht                                                                                  | Beschleunigt Forschung, erleichtert Zugänglichkeit, erhöht evtl. Zitationen                                                            | Publizieren an der Universität Münster | <https://www.uni-muenster.de/Publizieren/open-access/>                   |
| 3\. Forschungsergebnisse veröffentlichen    |     | Preprint Review / PCI / f1000research                   | Begutachtung von Forschungsartikeln wird unabhängig von Fachzeitschriften durchgeführt                                                                                                                                                                                                                 | Verbessert Qualitätskontrolle, löst Vendor-Lock-In von Forschenden bei kommerziellen Verlagen                                          | MüCOS                                  | <https://www.uni-muenster.de/MueCOS/index.html>                          |
| 3\. Forschungsergebnisse veröffentlichen    |     | Open Peer Review                                        | Gutachten werden bei Publikation oder für alle begutachteten Artikel veröffentlicht                                                                                                                                                                                                                    | Nachweis für tatsächlich stattfindende Qualitätskontrolle                                                                              | MüCOS                                  | <https://www.uni-muenster.de/MueCOS/index.html>                          |
| 3\. Forschungsergebnisse veröffentlichen    |     | Open Author Contributions                               | Beiträge der an einer Forschungsleistung Beteiligten werden klar kommuniziert (z.B. via CRediT)                                                                                                                                                                                                        | Klärt Verantwortlichkeiten, erleichtert Zuordnung von Leistungen (z.B. für Forschungsevaluation), verhindert Ehrenautor\*innenschaften | MüCOS                                  | <https://www.uni-muenster.de/MueCOS/index.html>                          |
| 4\. Forschungsergebnisse kommunizieren      |     | Open Science in der Lehre                               | Aspekte von Open Science werden im Rahmen von Seminaren, Vorlesungen, oder entsprechenden Prüfungsleistungen diskutiert oder vorgestellt                                                                                                                                                               | Bereitet Lernende auf steigende Anforderungen im Wissenschaftsbetrieb vor                                                              | MüCOS                                  | <https://www.uni-muenster.de/MueCOS/index.html>                          |
| 4\. Forschungsergebnisse kommunizieren      |     | Open Educational Resources                              | Lehrmaterialien werden online veröffentlicht                                                                                                                                                                                                                                                           | Verringert Diskriminierung, verbessert evtl. Lernresultate                                                                             | MüCOS                                  | <https://www.uni-muenster.de/MueCOS/index.html>                          |
| 4\. Forschungsergebnisse kommunizieren      |     | Science Communication                                   | Wissenschaftliche Befunde werden für die allgemeine Öffentlichkeit verständlich aufbereitet und erklärt                                                                                                                                                                                                | Erhöht Nachvollziehbarkeit von Wissenschaft und evtl. Vertrauen in Wissenschaft                                                        | Zentrum für Wissenschaftskommunikation | <https://www.uni-muenster.de/Religion-und-Politik/presse/personen.shtml> |
| 0\. Übergreifend                            |     | Evaluation von Forschung (Transparenz / TOP Guidelines) | Die Bewertung von Forschung verlagert sich von Quantität hin zur Qualität                                                                                                                                                                                                                              | Erhöht langfristig Qualität von Wissenschaft, bietet Alternative zu Zitationsmetriken                                                  | MüCOS                                  | <https://www.uni-muenster.de/MueCOS/index.html>                          |
